novo_projeto/urls.py
from django.conf.urls import url
from django.contrib import admin
from app.views import SetorList, SetorCreate, FuncionarioCreate

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^novosetor/$', SetorCreate.as_view(), name='novo_setor'),
    url(r'^novofuncionario/$', FuncionarioCreate.as_view(), name='novo_funcionario'),
    url(r'^setores/$', SetorList.as_view(), name='setores'),
]

app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

#
# class Departamento(models.Model):
#     nome = models.CharField(max_length=255)


# Create your models here.
class Setor(models.Model):
    nome = models.CharField(max_length=255)
    # departamento = models.ForeignKey(Departamento)

    def __unicode__(self):
        return self.nome


class Funcionario(models.Model):
    nome = models.CharField(max_length=255)
    setor = models.ForeignKey(Setor)

    def __unicode__(self):
        # return u"%s (%s/%s)".format(self.nome, self.setor.nome, self.setor.departamento.nome)
        return u"%s (%s/%s)".format(self.nome, self.setor.nome)

app/forms.py
from django.forms import ModelForm
from .models import Funcionario

class FuncionarioForm(ModelForm):
    class Meta:
        model = Funcionario
        fields = ['nome', 'setor']

app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, CreateView
from django.views.decorators.csrf import csrf_exempt

from .forms import FuncionarioForm
from .models import Setor, Funcionario


# Create your views here.
# @csrf_exempt
# def hello_world(request):
#     if request.method=='GET':
#         return HttpResponse('ola mundo GET')
#     elif request.method=='POST':
#         return HttpResponse('ola mundo POST')
#
#
# @method_decorator(csrf_exempt, name='dispatch')
# class HelloWorldView(View):
#     def get(self, request):
#         return HttpResponse('ola mundo GET')
#
#     def post(self, request):
#         return HttpResponse('ola mundo POST')
#

class SetorList(ListView):
    model = Setor
    context_object_name = 'setores'
    template_name = 'app/setores.html'


class SetorCreate(SuccessMessageMixin, CreateView):
    model = Setor
    fields = ['nome']
    template_name = 'app/novo_setor.html'
    success_url = '/setores'
    success_message = 'O setor foi cadastrado com sucesso'


class FuncionarioCreate(SuccessMessageMixin, CreateView):
    model = Funcionario
    form_class = FuncionarioForm
    # fields = ['nome', 'setor']
    template_name = 'app/novo_funcionario.html'
    success_url = '/setores'

    success_message = 'O funcionário foi cadastrado com sucesso'

app/templates/app/novo_funcionario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Setores</title>
</head>
<body>
<h1>SISHosp</h1>
<h2>Cadastro de funcionário</h2>

<form method="post" action=".">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Cadastrar</button>
</form>
</body>
</html>

app/templates/app/novo_setor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Setores</title>
</head>
<body>
<h1>SISHosp</h1>
<h2>Cadastro de setores</h2>

<form method="post" action=".">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Cadastrar</button>
</form>
</body>
</html>

app/templates/app/setores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Setores</title>
</head>
<body>
<h1>SISHosp</h1>
<h2>Lista de setores</h2>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'novo_setor' %}">Cadastrar setor</a>
<a href="{% url 'novo_funcionario' %}">Cadastrar funcionário</a>

    <ul>
    {% for setor in setores %}
        <li>
            {{ setor.nome }} -
            {% for funcionario in setor.funcionario_set.all %}
                {{ funcionario.nome }}{% if not forloop.last %}, {% else %}.{% endif %}
            {% endfor %}
        </li>

    {% endfor %}
    </ul>
</body>
</html>